services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.glance.rule=Host(`dashboard.adair.cloud`)"
        - "traefik.http.routers.glance.entrypoints=websecure"
        - "traefik.http.routers.glance.tls.certresolver=myresolver"
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8082:8080
    env_file: .env
    networks:
        - traefik_default
networks:
    traefik_default:
        name: traefik_default
        external: true
