---
- name: Ensure yum utils is installed
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Upgrade packages
  ansible.builtin.yum:
    name: '*'
    state: latest
    update-cache: true

- name: Check if reboot is required
  ansible.builtin.shell:
    cmd: "needs-restarting -r"
  changed_when: false
  failed_when: reboot_required.rc != 0 and reboot_required.rc != 1
  check_mode: false
  register: reboot_required

- name: Reboot if needed
  ansible.builtin.reboot:
  when: reboot_required.rc == 1
