[k3s_master]
k3s01.adair.cloud
[k3s_node]
k3s02.adair.cloud
k3s03.adair.cloud
[k3s_cluster:children]
k3s_master
k3s_node

[nextcloud]
nextcloud.adair.cloud

[jellyfin]
jellyfin.adair.cloud

[firewall]
firewall01.adair.cloud 

[tailscale_routers]
tsrouter01.adair.cloud 
tsrouter02.adair.cloud 

[docker_hosts]
docker01.adair.cloud 

[kasm]
kasm.adair.cloud

[monitoring]
kuma.adair.cloud

[nodejs]
kuma.adair.cloud

[prometheus]
prometheus.adair.cloud
