version: '3.9'
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual-budget
    ports:
      - '5006:5006'
    network_mode: service:tailscale
    depends_on:
      tailscale:
        condition: service_healthy
    volumes:
      - ./actual-data:/data
    restart: unless-stopped
  tailscale:
    hostname: money
    image: tailscale/tailscale:latest
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    volumes:
      - "./tailscale_var_lib:/var/lib"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
      - net_raw
    command: tailscaled
    ports:
      - "5006:5006"
