version: "3.3"
services:
  stirling-pdf:
    container-name: stirling-pdf
    image: frooodle/s-pdf:latest
    ports:
      - "8082:8080"
    volumes:
      - /usr/share/trainingData/eng.traineddata:/usr/share/tesseract-ocr/4.00/tessdata
    environment:
      APP_LOCALE: en_US
      APP_HOME_NAME: PDF Editor
      APP_HOME_DESCRIPTION: ""
      APP_NAVBAR_NAME: Stirling PDF
      APP_ROOT_PATH: /
