---
- name: Enable EPEL 
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Enable PowerTools
  ansible.builtin.command: dnf config-manager --set-enabled crb

- name: Ensure zsh and other programs I use be default are installed 
  ansible.builtin.dnf:
    name: zsh, zoxide, fzf, bat, cargo, thefuck
    state: present

- name: Install eza with cargo 
  community.general.cargo:
    name: eza 
    state: present 

- name: Ensure that my user account is created
  ansible.builtin.user:
    name: bpadair
    state: present
    create_home: true
    password: $y$j9T$rAC2aW1yL/PXNe66H9bQ/1$BXcvCUIM67I25Em037jHWvTu51qxxVuPojjocr2IKb/
    groups: wheel
    append: true
    shell: /usr/bin/zsh

- name: Ensure that .ssh directory is created
  ansible.builtin.file:
    path: /home/bpadair/.ssh
    state: directory
    owner: bpadair
    group: bpadair
    mode: 0755
  become: false

- name: Ensure that my SSH private key is on the machine
  ansible.builtin.copy:
    src: id_rsa 
    dest: /home/bpadair/.ssh/id_ecdsa
    owner: bpadair
    group: bpadair
    mode: 0600
  become: false

- name: Ensure that my public key is on the machine 
  ansible.builtin.copy:
    src: id_rsa.pub 
    dest: /home/bpadair/.ssh/id_ecdsa.pub
    owner: bpadair
    group: bpadair
    mode: 0644
  become: false

- name: Add my public key to authorized_keys
  ansible.posix.authorized_key:
    user: bpadair
    state: present
    key: "{{ lookup('file', '/home/bpadair/.ssh/id_ecdsa.pub') }}"

- name: Ensure that chezmoi is installed to manage my dotfiles
  block:
    - name: Determine the current chezmoi version 
      block:
        - name: Get latest releases
          ansible.builtin.uri:
            url: https://api.github.com/repos/twpayne/chezmoi/releases/latest
            return_content: true
          register: chezmoi_release_output
        - name: Set version
          ansible.builtin.set_fact:
            _chezmoi_version: "{{ chezmoi_release_output.json.tag_name }}"
      when: chezmoi_version == ""
      become: false
   
    - name: Set the chezmoi version
      ansible.builtin.set_fact:
        _chezmoi_version: "{{ chezmoi_version }}"
      when: chezmoi_version != ""
      become: false

    - name: Check if chezmoi is already installed
      ansible.builtin.command: chezmoi --version
      register: chezmoi_installed
      ignore_errors: true
      changed_when: false
      become: false
 
    - name: Set variables
      ansible.builtin.set_fact:
        chezmoi_install: "{{ chezmoi_installed.rc == 2 or not (_chezmoi_version in chezmoi_installed.stdout) }}"
        chezmoi_version_filtered: "{{ _chezmoi_version | regex_replace('^v', '') }}"
      become: false

    - name: Install chezmoi
      ansible.builtin.dnf:
        name: "https://github.com/twpayne/chezmoi/releases/download/v{{ chezmoi_version_filtered}}/chezmoi-{{ chezmoi_version_filtered }}-{{ chezmoi_redhat_architectures[ansible_architecture] }}.rpm"
        state: present
        disable_gpg_check: true
      when: chezmoi_install

- name: Initialize Chezmoi
  ansible.builtin.command: "chezmoi init --apply --verbose {{ chezmoi_init_url }}"
  when: chezmoi_init_url
  become: false
