galaxy_info:
  author: Brad Adair
  description: This is a role that manages the users on my servers.

  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: AlmaLinux
      versions:
        - all

  galaxy_tags: []

dependencies: []
